"""domain del test

Revision ID: 21f13d29d508
Revises: 33debf775a7f
Create Date: 2017-07-28 09:59:05.224392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21f13d29d508'
down_revision = '33debf775a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'domain', 'project', ['project_id'], ['id'])
    op.drop_column('domain', 'test_name')
    op.create_foreign_key(None, 'user_projects', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_projects', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.add_column('domain', sa.Column('test_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'domain', type_='foreignkey')
    # ### end Alembic commands ###
