"""domain add test

Revision ID: 33debf775a7f
Revises: 3bbc17df94f8
Create Date: 2017-07-28 09:57:37.047214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33debf775a7f'
down_revision = '3bbc17df94f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('test_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'domain', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'user_projects', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_projects', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.drop_constraint(None, 'domain', type_='foreignkey')
    op.drop_column('domain', 'test_name')
    # ### end Alembic commands ###
