"""modify project users table

Revision ID: eef6ffbf8677
Revises: 6b3f42045518
Create Date: 2017-06-30 17:54:11.377341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef6ffbf8677'
down_revision = '6b3f42045518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'domain', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'user_projects', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_projects', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.drop_constraint(None, 'domain', type_='foreignkey')
    # ### end Alembic commands ###
